package com.iridium.iridiumteams;

public enum LogType {
    TEAM_CREATE,
    TEAM_INVITE,
    TEAM_UNINVITE,
    TEAM_JOIN,
    TEAM_LEAVE,
    TEAM_PROMOTE,
    TEAM_DEMOTE,
    TEAM_KICK,
    TEAM_TRANSFER,
    TEAM_BANK_DEPOSIT,
    TEAM_BANK_WITHDRAW,
    TEAM_UPGRADE_PURCHASE,
    TEAM_BOOSTER_PURCHASE,
    TEAM_TRUST,
    TEAM_UNTRUST,
    TEAM_WARP_CREATE,
    TEAM_WARP_EDIT,
    TEAM_WARP_DELETE,
    TEAM_SETTINGS
}
